name: food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  slidable_button: ^1.0.1+1
  flutter_vector_icons: ^1.0.0
  flutter_easyloading: ^3.0.3
  flutter_form_builder: ^6.2.0
  textless: ^6.6.6
  get_cli: ^1.7.1
  get: ^4.6.0
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  shimmer_animation: ^2.1.0+1
  cached_network_image: ^3.2.0
  dio: ^4.0.6
  logger: ^1.1.0
  flutter_keyboard_visibility: ^5.2.0
  get_storage: ^2.0.3
  dio_logging_interceptor: ^1.0.1
  connectivity_plus: ^2.3.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Thin.ttf
          weight: 100

        - asset: assets/fonts/Kanit/Kanit-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Kanit/Kanit-Light.ttf
          weight: 300

        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
          weight: 400

        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
          weight: 500

        - asset: assets/fonts/Kanit/Kanit-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
          weight: 700

        - asset: assets/fonts/Kanit/Kanit-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Kanit/Kanit-Black.ttf
          weight: 900

get_cli:
  sub_folder: false
